orbs:
  slack: circleci/slack@3.4.2
version: 2.1
jobs:
  toxify:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install cairo for xhtml2pdf/svglib
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends libcairo2-dev pkg-config
      - run: pip install tox
      - run: pip uninstall -y numpy pandas scipy
      - run:
          no_output_timeout: 60m
          name: Run tox
          command: |
            PY="$(echo << parameters.python-version >> | tr -d '.')"
            tox -e "py${PY}"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - run: mkdir -p /tmp/circleci-artifacts /tmp/circleci-test-results
      - run:
          name: Save test results
          command: |
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} /tmp/circleci-test-results/ \;
          when: always
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts

workflows:
  version: 2
  test:
    jobs:
      - toxify:
          matrix:
            parameters:
              python-version: ["3.11", "3.12", "3.13"]
